@server=http://localhost:1337
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMmU4MzNiOWY0NzcxNjU4NWQ3ZmZjMCIsImlhdCI6MTU5Njg4NDEzOSwiZXhwIjoxNTk5NDc2MTM5fQ.5IzEn0bH1Fg8mG2hPVD9DhG8lbKGTWL98xPegaYdo2o

### REGISTER
POST {{server}}/auth/local/register
Content-Type: application/json

{
    "fullname": "test",
    "username": "test",
    "email": "test@devedu.tech",
    "password": "devedu.tech"
}


### LOGIN
POST {{server}}/auth/local
Content-Type: application/json

{
    "identifier": "AnotherUser",
    "password": "anotheruser"
}

### USER INFO
GET {{server}}/user/info
Authorization: Bearer {{token}} 


### USER UPDATE
PUT {{server}}/user/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fullname": "test devedu"
}