@server=http://localhost:1337
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMmU4MzNiOWY0NzcxNjU4NWQ3ZmZjMCIsImlhdCI6MTU5Njk4MTA0NiwiZXhwIjoxNTk5NTczMDQ2fQ.y0611E_jC_P2hhon0Gb-ijOZK2ICIEQ2vQH3J5oTqyE


### Find Event (Public)
GET {{server}}/events/photography-2020


### Find Event (Authorization)
GET {{server}}/events/photography-2020
Authorization: Bearer {{token}}